export const SECTION_LABELS: Record<string, string> = {
    "TOUR SPONTANEI": "TOUR SPONTANEI",
    "APPUNTAMENTI (Pianificazione)": "APPUNTAMENTI",
    "MISS CON APPUNTAMENTO": "MISS CON APPUNTAMENTO",
    "APPUNTAMENTI VERIFICHE DEL BISOGNO": "VERIFICHE DEL BISOGNO",
    "APPUNTAMENTI RINNOVI E INTEGRAZIONI": "RINNOVI/INTEGRAZIONI",
    "APPUNTAMENTI TELEFONICI": "APPUNTAMENTI TELEFONICI",
};

export const DB_SECTIONS = [
    "TOUR SPONTANEI",
    "APPUNTAMENTI (Pianificazione)",
    "MISS CON APPUNTAMENTO",
    "APPUNTAMENTI RINNOVI E INTEGRAZIONI",
    "APPUNTAMENTI VERIFICHE DEL BISOGNO",
    "APPUNTAMENTI TELEFONICI",
];

export function getSectionLabel(dbSection: string): string {
    return SECTION_LABELS[dbSection] || dbSection;
}
